const OR='https://openrouter.ai/api/v1/chat/completions';
const OR_MODELS=['openrouter/free','openai/gpt-oss-20b:free','qwen/qwen3-4b:free','google/gemma-3-4b-it:free'];
const GEMINI='gemini-2.5-flash', GROQ='llama-3.3-70b-versatile', CF='@cf/meta/llama-3.1-8b-instruct';
function json(x,s=200){return new Response(JSON.stringify(x,null,2),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'})}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}})}
export async function onRequestGet(){return json({success:true,service:'Yar Afghanistan Translation API',status:'online',endpoint:'/api/translate',method:'POST'})}
function n(s){return String(s??'').trim().toLowerCase().replace(/ي/g,'ی').replace(/ى/g,'ی').replace(/ك/g,'ک').replace(/ۀ/g,'ه').replace(/\s+/g,' ')}
const LANG={auto:'auto',detected:'auto',fa:'fa',dari:'fa',prs:'fa',persian:'fa',ps:'ps',pashto:'ps',en:'en',english:'en'};
function lang(v){return LANG[n(v)]||'auto'}
const P=[['سلام','fa','Hello','en','سلام','ps'],['سلام علیکم','fa','Peace be upon you','en','سلام علیکم','ps'],['خوب هستم','fa','I am fine','en','زه ښه یم','ps'],['خوبی؟','fa','How are you?','en','څنګه یې؟','ps'],['چطوری','fa','How are you?','en','څنګه یې؟','ps'],['تشکر','fa','Thank you','en','مننه','ps'],['ممنون','fa','Thank you','en','مننه','ps'],['خداحافظ','fa','Goodbye','en','خدای پامان','ps'],['صبح بخیر','fa','Good morning','en','سهار مو پخیر','ps'],['شب بخیر','fa','Good night','en','شپه مو پخیر','ps'],['بله','fa','Yes','en','هو','ps'],['نه','fa','No','en','نه','ps'],['سلام','ps','Hello','en','سلام','fa'],['زه ښه یم','ps','I am fine','en','من خوب هستم','fa'],['څنګه یې؟','ps','How are you?','en','چطوری؟','fa'],['مننه','ps','Thank you','en','تشکر','fa'],['خدای پامان','ps','Goodbye','en','خداحافظ','fa'],['hello','en','سلام','fa','سلام','ps'],['hi','en','سلام','fa','سلام','ps'],['how are you?','en','چطوری؟','fa','څنګه یې؟','ps'],['how are you','en','چطوری؟','fa','څنګه یې؟','ps'],['i am fine','en','خوب هستم','fa','زه ښه یم','ps'],['thank you','en','تشکر','fa','مننه','ps'],['thanks','en','تشکر','fa','مننه','ps'],['goodbye','en','خداحافظ','fa','خدای پامان','ps'],['good morning','en','صبح بخیر','fa','سهار مو پخیر','ps'],['good night','en','شب بخیر','fa','شپه مو پخیر','ps']];
function dict(t,f,to){const x=n(t);for(const [a,al,b,bl,c,cl] of P){if(n(a)===x&&al===f){if(to===bl)return b;if(to===cl)return c}}return null}
function prompt(t,f,to){const S=f==='fa'?'Afghan Dari/Persian':f==='ps'?'Pashto':f==='en'?'English':'the detected language';const T=to==='fa'?'Afghan Dari/Persian':to==='ps'?'Pashto':'English';return `Translate ONLY this text from ${S} to ${T}. Return ONLY the translation. Do not explain, chat, greet, or add anything. Preserve meaning and punctuation. Text:\n${t}`}
async function cf(env,p){if(!env?.AI?.run)return null;try{const r=await env.AI.run(CF,{messages:[{role:'system',content:'You are a strict translation engine. Return only the translation.'},{role:'user',content:p}],max_tokens:500});const a=r?.response||r?.result?.response||'';return a.trim()?{answer:a.trim(),provider:'Cloudflare Workers AI',model:CF}:null}catch{return null}}
async function gem(env,p){const k=String(env?.GEMINI_API_KEY||'').trim();if(!k)return null;try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI}:generateContent?key=${encodeURIComponent(k)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:'Strict translation engine. Return ONLY the translation.'}]},contents:[{role:'user',parts:[{text:p}]}],generationConfig:{temperature:.1,maxOutputTokens:500}})});const d=await r.json().catch(()=>({}));const a=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('').trim();return r.ok&&a?{answer:a,provider:'Google Gemini',model:GEMINI}:null}catch{return null}}
async function groq(env,p){const k=String(env?.GROQ_API_KEY||'').trim();if(!k)return null;try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${k}`,'Content-Type':'application/json'},body:JSON.stringify({model:GROQ,messages:[{role:'system',content:'Strict translation engine. Return ONLY the translation.'},{role:'user',content:p}],temperature:.1,max_tokens:500})});const d=await r.json().catch(()=>({}));const a=d?.choices?.[0]?.message?.content?.trim();return r.ok&&a?{answer:a,provider:'Groq',model:GROQ}:null}catch{return null}}
async function or(env,p){const k=String(env?.OPENROUTER_API_KEY||'').trim();if(!k)return null;for(const model of OR_MODELS){try{const r=await fetch(OR,{method:'POST',headers:{Authorization:`Bearer ${k}`,'Content-Type':'application/json','HTTP-Referer':'https://yar-afghanistan1.pages.dev','X-Title':'Yar Afghanistan Translator'},body:JSON.stringify({model,messages:[{role:'system',content:'Strict translation engine. Return ONLY the translation.'},{role:'user',content:p}],temperature:.1,max_tokens:500})});const d=await r.json().catch(()=>({}));const a=d?.choices?.[0]?.message?.content?.trim();if(r.ok&&a)return{answer:a,provider:'OpenRouter',model:d?.model||model}}catch{}}return null}
function detect(t){const x=n(t);if(/^[\x00-\x7F]*$/.test(x))return'en';if(/[څځږښګڼډړټ]+/.test(x)||/[ېۍښګڅژ]+/.test(x))return'ps';return'fa'}
export async function onRequestPost({request,env}){try{let b;try{b=await request.json()}catch{return json({success:false,error:'❌ درخواست JSON معتبر نیست.'},400)}const text=String(b?.text||b?.message||'').trim();if(!text)return json({success:false,error:'❌ متن خالی است.'},400);let from=lang(b?.source||b?.from||'auto'),to=lang(b?.target||b?.to||'en');if(to==='auto')return json({success:false,error:'❌ زبان مقصد را انتخاب کنید.'},400);if(from==='auto')from=detect(text);if(from===to)return json({success:true,reply:text,translation:text,provider:'same-language',source:from,target:to});const local=dict(text,from,to);if(local)return json({success:true,reply:local,translation:local,provider:'local',source:from,target:to});const p=prompt(text,from,to);for(const fn of [cf,gem,groq,or]){const r=await fn(env,p);if(r){const a=r.answer.replace(/^['“"](.*)['”"]$/s,'$1').trim();return json({success:true,reply:a,translation:a,provider:r.provider,model:r.model,source:from,target:to})}}return json({success:false,error:'❌ در حال حاضر سرویس‌های ترجمه در دسترس نیستند. لطفاً چند لحظه بعد دوباره تلاش کنید.',code:'NO_TRANSLATION_PROVIDER_AVAILABLE'},503)}catch(e){console.error(e);return json({success:false,error:'❌ خطای داخلی مترجم.'},500)}}
